//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorShareService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proposal()
        {
            this.ProposalMessages = new HashSet<ProposalMessage>();
        }
    
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public int FromUserID { get; set; }
        public int ToUserID { get; set; }
        public int StatusID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> ProposedTime { get; set; }
        public bool Active { get; set; }
        public Nullable<decimal> AproxDuration { get; set; }
        public Nullable<decimal> ProposedPrice { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> UpdatedByUserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Service Service { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalMessage> ProposalMessages { get; set; }
    }
}
