//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorShareService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int ID { get; set; }
        public Nullable<bool> ShareLocation { get; set; }
        public Nullable<bool> EnableNotifications { get; set; }
        public Nullable<bool> ShowContactNumber { get; set; }
        public Nullable<bool> ShowContactEmail { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
