//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorShareService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Appointment = new HashSet<Appointment>();
            this.Appointment1 = new HashSet<Appointment>();
            this.Bug = new HashSet<Bug>();
            this.Comment = new HashSet<Comment>();
            this.Preference = new HashSet<Preference>();
            this.Proposal = new HashSet<Proposal>();
            this.Proposal1 = new HashSet<Proposal>();
            this.Rating = new HashSet<Rating>();
            this.Rating1 = new HashSet<Rating>();
            this.Service = new HashSet<Service>();
            this.Suggestion = new HashSet<Suggestion>();
            this.UserCategory = new HashSet<UserCategory>();
            this.UserDenunce = new HashSet<UserDenunce>();
            this.UserFavourite = new HashSet<UserFavourite>();
            this.UserFavourite1 = new HashSet<UserFavourite>();
        }
    
        public int ID { get; set; }
        public int UserType { get; set; }
        public string Email { get; set; }
        public string EncPassword { get; set; }
        public System.DateTime ExpDate { get; set; }
        public bool Active { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public Nullable<long> MobileNumber { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string CompanyName { get; set; }
        public decimal CompanyCoordX { get; set; }
        public decimal CompanyCoordY { get; set; }
        public Nullable<int> CNumServices { get; set; }
        public string Contractor_website { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> CNumOfRates { get; set; }
        public Nullable<double> CAverageRate { get; set; }
        public Nullable<double> PricePerHour { get; set; }
    
        public virtual ICollection<Appointment> Appointment { get; set; }
        public virtual ICollection<Appointment> Appointment1 { get; set; }
        public virtual ICollection<Bug> Bug { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Preference> Preference { get; set; }
        public virtual ICollection<Proposal> Proposal { get; set; }
        public virtual ICollection<Proposal> Proposal1 { get; set; }
        public virtual ICollection<Rating> Rating { get; set; }
        public virtual ICollection<Rating> Rating1 { get; set; }
        public virtual ICollection<Service> Service { get; set; }
        public virtual ICollection<Suggestion> Suggestion { get; set; }
        public virtual ICollection<UserCategory> UserCategory { get; set; }
        public virtual ICollection<UserDenunce> UserDenunce { get; set; }
        public virtual ICollection<UserFavourite> UserFavourite { get; set; }
        public virtual ICollection<UserFavourite> UserFavourite1 { get; set; }
    }
}
