//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorShareService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Appointment = new HashSet<Appointment>();
            this.Comment = new HashSet<Comment>();
            this.Proposal = new HashSet<Proposal>();
            this.Rating = new HashSet<Rating>();
            this.Task = new HashSet<Task>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int StatusID { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public decimal CoordX { get; set; }
        public decimal CoordY { get; set; }
        public int ClientID { get; set; }
        public int CategoryID { get; set; }
    
        public virtual ICollection<Appointment> Appointment { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Proposal> Proposal { get; set; }
        public virtual ICollection<Rating> Rating { get; set; }
        public virtual User User { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Task> Task { get; set; }
    }
}
